name: inception
services:
    mariadb:
        build: requirements/mariadb
        networks:
            - net
        command:
          - mysqld_safe
    nginx:
        depends_on: 
            - wordpress
            - mariadb 
        volumes:
            - wordpress:/wordpress
        hostname: lomeniga.42.fr
        build: requirements/nginx
        command:
            - nginx
            - -g
            - daemon off;
        networks:
            - net
        ports:
            - 4443:443
        expose: 
          - 443
        secrets:
            - server.crt
            - server.key
    wordpress:
        depends_on:
          - mariadb
        build: requirements/wordpress
        volumes:
          - wordpress:/wordpress
        networks:
            - net
        command:
            - php-fpm8
            - -F

networks:
    net:

volumes:
    wordpress:
      driver_opts:
        type: none
        o: bind
        device: /tmp/wordp
    database:

secrets:
    server.crt:
        file: server.crt
    server.key:
        file: server.key

configs:
    nginx:
        external: true
