name: inception
services:
    mariadb:
        build:
          context: requirements/mariadb
          args:
            DB_PASSWD: $DB_PASSWD
        networks:
            - net
        command:
          - mysqld_safe
        volumes:
          - db:/var/lib/mysql/wpdb
    nginx:
        depends_on: 
            - wordpress
            - mariadb 
        volumes:
            - wordpress:/wordpress
        hostname: lomeniga.42.fr
        build: requirements/nginx
        command:
            - nginx
            - -g
            - daemon off;
        networks:
            - net
        ports:
            - 443:443
        expose: 
          - 443
        secrets:
            - server.crt
            - server.key
    wordpress:
        environment:
          WP_PWD:
        depends_on:
          - mariadb
        build:
          context: requirements/wordpress
          args:
            DB_PASSWD: ${DB_PASSWD}
            WP_PWD: ${WP_PWD}
        volumes:
            - wordpress:/wordpress
        command:
          - php-fpm8
          - -F
        networks:
            - net

networks:
    net:

volumes:
    wordpress:
      external: false
      driver_opts:
        type: none
        o: bind
        device: /home/lomeniga/data/wordp
    db:
      external: false
      driver_opts:
        type: none
        o: bind
        device: /home/lomeniga/data/db

secrets:
    server.crt:
        file: cert.pem
    server.key:
        file: key.pem

configs:
    nginx:
        external: true
